In [1]:
import numpy as np

In [6]:
arr=np.arange(24).reshape(2,3,4)

In [4]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
arr.flat

In [12]:
arr.flatten(order="C")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
arr2=np.arange(12).reshape(3,4)

In [15]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
np.transpose(arr2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [17]:
type(arr)

numpy.ndarray

In [21]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
arr.shape

(2, 3, 4)

In [26]:
arr3=np.transpose(arr)

In [27]:
arr3.shape

(4, 3, 2)

In [28]:
arr4=np.transpose(arr3)

In [29]:
arr4.shape

(2, 3, 4)

In [30]:
arr4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [31]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [33]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [35]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
arr6=np.arange(24)

In [37]:
np.split(arr6,6)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19]),
 array([20, 21, 22, 23])]

In [38]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
np.split(arr6,[1,6,9,15,19])

[array([0]),
 array([1, 2, 3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14]),
 array([15, 16, 17, 18]),
 array([19, 20, 21, 22, 23])]

In [43]:
mySpeArr=np.split(arr6,[1,5,9])[-1]

In [44]:
mySpeArr

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
append

In [49]:
a=np.array([[1,5,6],[8,9,9]])

In [50]:
a

array([[1, 5, 6],
       [8, 9, 9]])

In [52]:
np.append(a, [1,9,11])

array([ 1,  5,  6,  8,  9,  9,  1,  9, 11])

In [53]:
a

array([[1, 5, 6],
       [8, 9, 9]])

In [56]:
np.append(a, [[1,9,10]], axis=0)

array([[ 1,  5,  6],
       [ 8,  9,  9],
       [ 1,  9, 10]])

In [58]:
np.append(a, [[1],[9]], axis=1)

array([[1, 5, 6, 1],
       [8, 9, 9, 9]])

In [59]:
a

array([[1, 5, 6],
       [8, 9, 9]])

In [60]:
np.insert(a, 2,[1,5,9])

array([1, 5, 1, 5, 9, 6, 8, 9, 9])

In [61]:
a

array([[1, 5, 6],
       [8, 9, 9]])

In [62]:
np.insert(a,1, [[1,9,10]], axis=0)

array([[ 1,  5,  6],
       [ 1,  9, 10],
       [ 8,  9,  9]])

In [63]:
np.insert(a,2, [[1],[9]], axis=1)

array([[1, 5, 1, 9, 6],
       [8, 9, 1, 9, 9]])

In [ ]:
delete

In [66]:
aa=np.arange(12).reshape(3,4)

In [67]:
aa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
np.delete(aa,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [70]:
np.delete(aa,1, axis=0 )

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [71]:
aa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
np.delete(aa, 2, axis=1)

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

In [74]:
a = np.array([5,2,6,2,7,5,6,8,2,9]) 

In [75]:
np.unique(a)

array([2, 5, 6, 7, 8, 9])

In [77]:
arr = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])

In [81]:
arr

array([[1, 0, 0],
       [1, 0, 0],
       [2, 3, 4]])

In [82]:
np.unique(arr,axis=0)

array([[1, 0, 0],
       [2, 3, 4]])

In [83]:
np.unique(arr,axis=1)

array([[0, 0, 1],
       [0, 0, 1],
       [3, 4, 2]])

In [84]:
a=np.array([[1,1,0],[1,1,0],[1,1,4]])

In [85]:
a

array([[1, 1, 0],
       [1, 1, 0],
       [1, 1, 4]])

In [87]:
np.unique(a,axis=1, return_index=True)

(array([[0, 1],
        [0, 1],
        [4, 1]]),
 array([2, 0], dtype=int64))

In [92]:
a=np.array([[3,7,5],[9,1,7]])

In [93]:
a

array([[3, 7, 5],
       [9, 1, 7]])

In [94]:
np.sort(a)

array([[3, 5, 7],
       [1, 7, 9]])

In [98]:
a

array([[3, 7, 5],
       [9, 1, 7]])

In [97]:
np.sort(a, axis=1)

array([[3, 5, 7],
       [1, 7, 9]])

In [99]:
np.sort(a)

array([[3, 5, 7],
       [1, 7, 9]])

In [ ]:
where

In [101]:
arr10=np.arange(10)

In [102]:
arr10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
arr10>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [104]:
np.where(arr10>5)

(array([6, 7, 8, 9], dtype=int64),)

In [105]:
np.where(arr10>5, arr10*10,arr10)

array([ 0,  1,  2,  3,  4,  5, 60, 70, 80, 90])

In [106]:
arr10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.where(arr10<7,arr10,arr10+10)

array([ 0,  1,  2,  3,  4,  5,  6, 17, 18, 19])

In [ ]:
extract

In [111]:
x = np.arange(9).reshape(3, 3)

In [112]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [123]:
kural=(np.add(x,5)==8)|(np.add(x,6)>7)&()|()

In [124]:
kural

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [125]:
np.extract(kural,x)

array([2, 3, 4, 5, 6, 7, 8])

In [126]:
a=np.arange(12).reshape(3,4)

In [128]:
for i in a:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [130]:
b=np.arange(12).reshape(3,4)

In [132]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
for i in np.nditer(b,  order="F"):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [134]:
arr=np.arange(12)

In [135]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [138]:
for i in np.nditer(arr, op_flags=["readwrite"]):
    i[...]=i*10

In [139]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [ ]:
Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3

In [141]:
arr1=np.arange(256*256*3).reshape(256,256,3)

In [142]:
arr1.shape

(256, 256, 3)

In [146]:
arr3=np.arange(3)

In [148]:
arr3.shape

(3,)

In [149]:
arr2=arr1+arr3

In [151]:
arr2.shape

(256, 256, 3)

In [156]:
arrR=np.random.randint(100, size=(5))

In [157]:
arrR

array([30, 88,  2, 78, 31])

In [158]:
arrR=np.random.randint(100, size=(5,2))

In [159]:
arrR

array([[96, 10],
       [76, 15],
       [31, 24],
       [36, 17],
       [31, 83]])

In [175]:
np.random.seed(345)

In [176]:
np.random.randint(20)

16

In [169]:
np.random.choice(np.arange(12), size=(2,1))

array([[7],
       [7]])