## Practice: NumPy and Pandas

### 1-NumPy

In [1]:
import numpy as np

In [2]:
#1) Verilen listeyi NumPy arrayi haline getirelim.
liste = [3,5,9,11,94,1,7]
arr= np.array(liste)
print(arr)

[ 3  5  9 11 94  1  7]


In [3]:
type(arr)

numpy.ndarray

In [4]:
#2) Bu verilen Listeyi NumPy arrayi haline getirelim ve bir önceki soru ile karşılaştıralım.
liste2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array(liste2)

In [5]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# array kaça kaç...
arr2.shape

(3, 3)

In [7]:
# kaç boyutlu olduğuna bakmak için
arr2.ndim

2

In [8]:
# arr arrayinin 2 indexteki elemanı
arr[2]

9

In [9]:
# arr2 arrayinin 2. indexteki elemanı
arr2[2]

array([7, 8, 9])

In [10]:
#3) 0'dan 10'a kadar olan sayılardan(10 dahil değil) oluşan bir array oluşturalım.
arr3=np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#4) 1'den 100'e kadar(100 dahil değil) 5'er 5'er atlayarak bütün değerleri array haline getirip yazdıralım.
arr4= np.arange(1,100,5)
arr4

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [12]:
#5) Sadece 0'lardan oluşan 8 elemanlı ve tek boyutlu bir array oluşturalım.
arr5= np.zeros(8)
arr5

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
#6) Sadece 0'lardan oluşan 16 elemanlı ve (4,4) boyutlarında bir zeros arrayi oluşturalım.,
arr6= np.zeros((4,4))
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# reshape ile alternatif çözüm
arr16= np.zeros(16).reshape(4,4)
arr16

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#7) Sadece 1'lerden oluşan 5 elemanlı bir array oluşturalım.
arr7= np.ones(5)
arr7

array([1., 1., 1., 1., 1.])

In [16]:
#8) Sadece 1'lerden oluşan 15 elemanlı ve (3,5) boyutlarında bir ones arrayi oluşturalım.
arr8= np.ones((3,5))
arr8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#alternatif
arr88=np.ones(15).reshape(3,5)
arr88

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
#9) 0'lardan oluşan ve sadece sol üst - sağ alt diagonelinde 1'ler bulunan (6,6) boyutlarında bir array oluşturalım. ("Birim Matris oluşturuyoruz.") 
# (Tip : eye metodu)
arr9= np.eye(6,6)  # sadece 6 yazsak da olurdu çünkü kare matris
arr9

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
#10) 100 ile 500 arasında lineer(düzenli) artış yapan 81 elemanlı bir array oluşturalım
arr10= np.linspace(100, 500, num=81)
arr10

array([100., 105., 110., 115., 120., 125., 130., 135., 140., 145., 150.,
       155., 160., 165., 170., 175., 180., 185., 190., 195., 200., 205.,
       210., 215., 220., 225., 230., 235., 240., 245., 250., 255., 260.,
       265., 270., 275., 280., 285., 290., 295., 300., 305., 310., 315.,
       320., 325., 330., 335., 340., 345., 350., 355., 360., 365., 370.,
       375., 380., 385., 390., 395., 400., 405., 410., 415., 420., 425.,
       430., 435., 440., 445., 450., 455., 460., 465., 470., 475., 480.,
       485., 490., 495., 500.])

In [20]:
#11) 50 ile 100 arasında 20 tane random integer sayı döndürerek bir array oluşturalım.
arr11=np.random.randint(50,100, 20)
arr11

array([58, 79, 99, 94, 58, 55, 54, 64, 87, 76, 67, 67, 74, 62, 98, 60, 76,
       54, 90, 63])

In [21]:
#12) 0'dan 25'e kadar(25 dahil değil) sayılardan oluşan tek boyutlu bir array oluşturalım ve arr değişkenine atayalım.
# arr değişkenimizin shape'ini değiştirelim ve (5,5) yapalım

arr= np.arange(25)
arr12=arr.reshape(5,5)
arr12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
#13) [10, 49, 41, 17, 12 , 2, 46,  3, 19, 39, 9, 55]
# Yukarıda liste halinde verilen sayılarla array oluşturalım. Ardından minimum değerini maksimum değerini ve bu değerlerin kaçıncı indexlerde olduğunu bulalım.
arr13=np.array([10, 49, 41, 17, 12 , 2, 46,  3, 19, 39, 9, 55])
print(arr13.min())
print(arr13.max())


2
55


In [23]:
#indexler
arr13.argmax()

11

In [24]:
arr13.argmin()

5

In [25]:
#14) [69, 28, 92, 81, 61, 56, 92, 21, 67, 68, 75, 31, 95, 98, 56, 51, 81, 94, 63, 38, 36, 62, 94, 72, 92, 94, 62, 27, 51, 26, 91, 78, 74, 73,66, 64]
# Yukarıda liste halinde verilen 36 değerden önce bir array oluşturalım. Ardından (3,12) shape'ine dönüştürelim ve shape'in değişip değişmediğini kontrol edelim.
# Ek olarak dtype'ını da kontrol edip ne tür elemanlardan oluştuğunu kontrol edelim.

arr14=np.array([69, 28, 92, 81, 61, 56, 92, 21, 67, 68, 75, 31, 95, 98, 56, 51, 81, 94, 63, 38, 36, 62, 94, 72, 92, 94, 62, 27, 51, 26, 91, 78, 74, 73,66, 64])

In [26]:
arr14=arr14.reshape(3,12)

In [27]:
arr14.shape

(3, 12)

In [28]:
#15) 0'dan 20 (20 dahil değil)'ye kadar olan sayıları array olarak arr adında bir değişkene atayalım.
arr15= np.arange(20)
arr15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
#16) arr arrayinin içinden 3. ve 8.indexleri(8 dahil değil) arasındaki sayıları çekelim.
arr15[3:8]

array([3, 4, 5, 6, 7])

In [30]:
#17) arr arrayimizin 10. ve 15.indexleri(15 dahil değil) arasındaki değerleri 500 yapalım (BroadCasting)

arr15[10:15]=500
arr15

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 500, 500, 500,
       500, 500,  15,  16,  17,  18,  19])

In [31]:
#18) arr arayinin 15.indexinden sonraki indexlerindeki sayıları sliced_arr adında bir değişkene atayalım.
sliced_arr=arr15[16:]
sliced_arr

array([16, 17, 18, 19])

In [32]:
#19) sliced_arr arrayi içindeki  bütün değerleri 999 yapalım.
sliced_arr[:]=999
sliced_arr

array([999, 999, 999, 999])

In [33]:
arr15  # değişkende bir bölge sliced_arr ile değişmiş oldu.

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 500, 500, 500,
       500, 500,  15, 999, 999, 999, 999])

In [34]:
#20) arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45])) koduyla arr_2d adında 2 boyutlu bir array oluşturalım ve shapeine bakalım.

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d.shape

(3, 3)

In [36]:
#21) arr_2d arrayinin 1.indexini bulalım.
arr_2d[1]

array([20, 25, 30])

In [37]:
#22) arr_2d arrayinin içinden tam olarak 40 sayısını çekelim
arr_2d[2,1]  # alternatif [2][1]

40

In [38]:
#23) 0'dan 10'a kadar rakamlardan oluşan arr adında bir array oluşturalım. Ardından bu arrayi kendisiyle toplayalım.

arr=np.arange(10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
# Oluşturduğumuz arr arrayini gene arr arrayi ile çarpalım.
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [40]:
#24) 0 ile 20 arasından rastgele 5 sayıdan oluşan bir array oluşturalım ve arr adındaki değişkene atayalım. 
# Ardından arr değişkenindeki her bir değerin karesini alalım.
arr=np.random.randint(0,20, 5)
arr

array([ 8,  5, 18, 10, 13])

In [41]:
arr**2


array([ 64,  25, 324, 100, 169], dtype=int32)

### 2-Pandas

In [42]:
# 25) pandası import edelim
import pandas as pd

In [43]:
#26) Pandas kütüphanesi aracılığıyla datasetimizi okutalım ve okuttuğumuz datasetini df adlı bir değişkene atayıp ekrana yazdıralım
df = pd. read_csv ("users.csv")   # veya df= pd.read_csv("C:\Users\admin\Desktop\Python dersler\Dersler\MyNotes\users.csv")

In [44]:
df.head()

Country or area           Subregion    Region Internet users     Population
0           China        Eastern Asia      Asia  1,010,740,000  1,427,647,786
1           India       Southern Asia      Asia    833,710,000  1,352,642,280
2   United States    Northern America  Americas    312,320,000    327,096,265
3       Indonesia  South-eastern Asia      Asia    196,000,000    267,670,543
4          Brazil       South America  Americas    160,010,801    209,469,323

In [45]:
df.describe()

Country or area  Subregion  Region Internet users     Population
count              214        214     214            214            212
unique             214         22       5            214            212
top              China  Caribbean  Africa  1,010,740,000  1,427,647,786
freq                 1         20      55              1              1

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Country or area  214 non-null    object
 1   Subregion        214 non-null    object
 2   Region           214 non-null    object
 3   Internet users   214 non-null    object
 4   Population       212 non-null    object
dtypes: object(5)
memory usage: 8.5+ KB


In [47]:
#27) df adıyla çektiğimiz DataFrame'in shape'ine bakarak toplamda kaç tane verimiz olduğunu bulalım.
df.shape

(214, 5)

In [48]:
#28) df adıyla çektiğimiz DF'nin ilk 5 satırınıi görelim
df.head(5)

Country or area           Subregion    Region Internet users     Population
0           China        Eastern Asia      Asia  1,010,740,000  1,427,647,786
1           India       Southern Asia      Asia    833,710,000  1,352,642,280
2   United States    Northern America  Americas    312,320,000    327,096,265
3       Indonesia  South-eastern Asia      Asia    196,000,000    267,670,543
4          Brazil       South America  Americas    160,010,801    209,469,323

In [49]:
# 29) son 5...
df.tail(5)

Country or area       Subregion    Region  \
209  Saint Helena, Ascension and Tristan da Cunha  Western Africa    Africa   
210                              Falkland Islands   South America  Americas   
211                                    Montserrat       Caribbean  Americas   
212                             Wallis and Futuna       Polynesia   Oceania   
213                                          Niue       Polynesia   Oceania   

    Internet users Population  
209          2,906      6,035  
210          2,881      3,234  
211          2,833      4,993  
212          1,383     11,661  
213          1,034      1,620

In [50]:
#30) df'nin içinde her bir sütunda kaç tane nan değer olduğuna bakalım.
df.isna().sum()  # kolonların null değerleri

Country or area    0
Subregion          0
Region             0
Internet users     0
Population         2
dtype: int64

In [51]:
# 31) df'deki toplam nan sayısı
df.isna().sum().sum()  # tüm df'nin null değerleri

2

In [52]:
# 32) type'larına bakalım
df.dtypes  # burada int olması gerekenleri de object gösteriyor. Onların değişmesi lazım

Country or area    object
Subregion          object
Region             object
Internet users     object
Population         object
dtype: object

In [53]:
#33) df'nin içindeki farklı Region ve Subregion sayısını bulalım
df["Region"].unique()

array(['Asia', 'Americas', 'Africa', 'Europe', 'Oceania'], dtype=object)

In [54]:
#veya alternatif
df.Region.unique()

array(['Asia', 'Americas', 'Africa', 'Europe', 'Oceania'], dtype=object)

In [55]:
df.Subregion.unique()

array(['Eastern Asia', 'Southern Asia', 'Northern America',
       'South-eastern Asia', 'South America', 'Western Africa',
       'Eastern Europe', 'Western Asia', 'Western Europe',
       'Southern Europe', 'Northern Europe', 'Northern Africa',
       'Southern Africa', 'Australia, New Zealand', 'Eastern Africa',
       'Central Asia', 'Middle Africa', 'Caribbean', 'Central America',
       'Melanesia', 'Polynesia', 'Micronesia'], dtype=object)

In [56]:
#34) "Internet users" sütunun object olan type'ını integer olarak değiştirelim.

# Sütun adında arada boşluk olduğu için tırnak gerekiyor
df["Internet users"]=df["Internet users"].str.replace(",", "").astype("int64")  

In [57]:
df.head()

Country or area           Subregion    Region  Internet users     Population
0           China        Eastern Asia      Asia      1010740000  1,427,647,786
1           India       Southern Asia      Asia       833710000  1,352,642,280
2   United States    Northern America  Americas       312320000    327,096,265
3       Indonesia  South-eastern Asia      Asia       196000000    267,670,543
4          Brazil       South America  Americas       160010801    209,469,323

In [58]:
#35) Benzer bir şekilde "Population" için type değişimi yapalım

# önce nan değerlerden kurtulmamız gerekiyor.
df.dropna(inplace=True)

In [59]:
df["Population"]=df["Population"].str.replace(",", "").astype("int64")  

In [60]:
df.head()

Country or area           Subregion    Region  Internet users  Population
0           China        Eastern Asia      Asia      1010740000  1427647786
1           India       Southern Asia      Asia       833710000  1352642280
2   United States    Northern America  Americas       312320000   327096265
3       Indonesia  South-eastern Asia      Asia       196000000   267670543
4          Brazil       South America  Americas       160010801   209469323

In [61]:
df.dtypes

Country or area    object
Subregion          object
Region             object
Internet users      int64
Population          int64
dtype: object

In [62]:
# 36) "Country or area" sütununu index olarak atayalım

df.set_index("Country or area", inplace=True)   # sayı olan idexlerden kurtulduk.

In [63]:
df.head()

Subregion    Region  Internet users  Population
Country or area                                                          
China                  Eastern Asia      Asia      1010740000  1427647786
India                 Southern Asia      Asia       833710000  1352642280
United States      Northern America  Americas       312320000   327096265
Indonesia        South-eastern Asia      Asia       196000000   267670543
Brazil                South America  Americas       160010801   209469323

In [64]:
#37) Türkiye için mevcut bilgileri getirelim
df.loc["Turkey"]   # Turkey sütun bilgisi

Subregion         Southern Europe
Region                     Europe
Internet users           69945905
Population               82340088
Name: Turkey, dtype: object