### Practice: NumPy

In [2]:
import numpy as np

In [2]:
#Bir satır (row) olarak array oluşturma
arr = np.array([1,2,3])
print(arr)
type(arr)

[1 2 3]


numpy.ndarray

In [4]:
arr

array([1, 2, 3])

In [3]:
l=[1,2,3]
print(l)
type(l)

[1, 2, 3]


list

In [5]:
#Bir column (3x1) olarak vektör oluşturma
arr = np.array([[100],[200],[30]])
arr

array([[100],
       [200],
       [ 30]])

In [6]:
arr.shape

(3, 1)

In [9]:
# Matris oluşturma 
myArr = np.array([[17,21,18,11],[43,57,36,231],[911,65,831,117]])
print(myArr)
myArr

[[ 17  21  18  11]
 [ 43  57  36 231]
 [911  65 831 117]]


array([[ 17,  21,  18,  11],
       [ 43,  57,  36, 231],
       [911,  65, 831, 117]])

In [8]:
myArr.shape

(3, 4)

In [10]:
# ZEROS
# 3 x 4 bir matris oluşturma
ze = np.zeros([3,4], dtype="float32") # değerlerin tipi default(varsayılan) float64 değer
ze

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [11]:
type(ze)

numpy.ndarray

In [12]:
ze=np.zeros((3,4), dtype="int")  #dtype'ını  değiştiridik.

In [13]:
ze

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
ze.astype("float32")  # tipini bu şekilde de değiştirebiliriz.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [15]:
# ONES
# 3 x 4 bir matris oluşturma
on = np.ones([4,4], dtype="int")
on

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
# EYE birim matris     (Burada 1'ler diagonal yerleşiyor, diğer taraflar 0 ile doluyor. Kare matris oluyor)
# 4 x 4 bir matris oluşturma
ey = np.eye(4)
ey

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.full((3,2), 88)   # önce boyut sonra matrisi neyle doldurmak istediğimizi yazıyoruz.

array([[88, 88],
       [88, 88],
       [88, 88]])

In [19]:
np.full((3,2), np.NaN)  # NaN değerle de doldurabiliriz.

array([[nan, nan],
       [nan, nan],
       [nan, nan]])

In [20]:
rowArr= np.array([9,8,7,6,5,4,3,2,1])
mat = np.array([[90,80,70],[60,50,40],[30,20,10]])

In [21]:
mat.shape

(3, 3)

In [22]:
mat.ndim  # kaç boyutlu olduğuna bakıyoruz.

2

In [23]:
# tüm elemanların seçimi, baştan başla sona kadar, sondaki de dahil.
rowArr[:]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [24]:
rowArr[:4]  # 4.indextekine kadar

array([9, 8, 7, 6])

In [25]:
# +. indexten sona kadar
rowArr[4:]

array([5, 4, 3, 2, 1])

In [26]:
# Son elemanın getirilmesi
rowArr[-1]

1

In [27]:
mat

array([[90, 80, 70],
       [60, 50, 40],
       [30, 20, 10]])

In [28]:
# Matrisin 2. satırdaki 2. kolonuna ait eleman (50 değeri)
mat[1,1]

50

In [29]:
mat[:2,:]  # virgülden önce satır, sonrası sütun

array([[90, 80, 70],
       [60, 50, 40]])

In [30]:
mat[:,1:2] # satırların hepsi ama sadece 1. indexteki sütun

array([[80],
       [50],
       [20]])

In [ ]:
mat.reshape(1,9)   # matrisin boyutunu değiştiriyoruz.Ancak öncekiyle uyumlu olmalı(3x3, 9x1 vs.)

In [32]:
mat1=mat.reshape(1,9)  #yeni bir değişene atamazsak kalıcı olmaz.

In [31]:
# Satır ve kolon sayısının veren metod mat için
print(f"satır sayısı: {mat.shape[0]},\nsütun sayısı: {mat.shape[1]}")

satır sayısı: 3,
sütun sayısı: 3


In [33]:
# Satır ve kolon sayısının veren metod mat1 için
print(f"satır sayısı: {mat1.shape[0]},\nsütun sayısı: {mat1.shape[1]}")

satır sayısı: 1,
sütun sayısı: 9


In [34]:
# Toplam eleman sayısı (size)
print(mat.size)
# Boyut sayısı 
print(mat.ndim)

9
2


In [35]:
np.random.seed(1)  # random değeriler aynı gelsin diye

In [38]:
a=np.random.normal(2.0, # ortalama 
                3.0, # standart sapma
                5    # Değer adet
                 )

In [39]:
a

array([2.22448117, 4.0782978 , 8.21640274, 3.99073904, 5.57696743])

In [40]:
np.random.seed(22)
m1=np.random.randint(15,size=(4,4))  # içindeki elemanlar randomly 15'e kadar değer alabilir
m2=np.random.randint(5,size=(4,4))   # # içindeki elemanlar randomly 5'e kadar değer alabilir

In [41]:
m1

array([[ 5,  4, 12,  0],
       [ 4,  6,  6, 11],
       [ 4,  8,  4, 13],
       [ 2, 14, 12, 13]])

In [42]:
m2

array([[0, 2, 2, 1],
       [0, 0, 3, 4],
       [2, 2, 1, 1],
       [3, 3, 2, 3]])

In [43]:
# İki matrisin toplanması
print(np.add(m1, m2))

[[ 5  6 14  1]
 [ 4  6  9 15]
 [ 6 10  5 14]
 [ 5 17 14 16]]


In [44]:
# ya da 
m1+m2

array([[ 5,  6, 14,  1],
       [ 4,  6,  9, 15],
       [ 6, 10,  5, 14],
       [ 5, 17, 14, 16]])

In [47]:
np.subtract(m1, m2) # matriste çıkarma işlemi

array([[ 5,  2, 10, -1],
       [ 4,  6,  3,  7],
       [ 2,  6,  3, 12],
       [-1, 11, 10, 10]])

In [48]:
m1-m2

array([[ 5,  2, 10, -1],
       [ 4,  6,  3,  7],
       [ 2,  6,  3, 12],
       [-1, 11, 10, 10]])

In [49]:
# Matris eleman elemana çarpımi
m1 * m2

array([[ 0,  8, 24,  0],
       [ 0,  0, 18, 44],
       [ 8, 16,  4, 13],
       [ 6, 42, 24, 39]])

In [51]:
np.dot(m1,m2)   # matris çarpım. 
#Burada birinin satır sayısı ile diğerinin sütun sayısı denk olmalı(örneğin, (5,3) *(3,100) = (5,100) )

array([[ 24,  34,  34,  33],
       [ 45,  53,  54,  67],
       [ 47,  55,  62,  79],
       [ 63,  67,  84, 109]])

In [52]:
m1@m2   # bu da matris çarpımı. dot() yerine @ işaretiyle de yapılabilir.

array([[ 24,  34,  34,  33],
       [ 45,  53,  54,  67],
       [ 47,  55,  62,  79],
       [ 63,  67,  84, 109]])

In [53]:
m1*10 # tüm elemanları 10 ile çarptık.

array([[ 50,  40, 120,   0],
       [ 40,  60,  60, 110],
       [ 40,  80,  40, 130],
       [ 20, 140, 120, 130]])

In [3]:
# eleman işlemleri
np.random.seed(1)
myMat=np.random.randint(10,size=(3,2))   # 10'a kadar random sayılarla 3x2 matris
myMat

array([[5, 8],
       [9, 5],
       [0, 0]])

In [4]:
myMat.shape

(3, 2)

In [6]:
myMat.ndim

2

In [10]:
func = lambda x: x ** 2   # tek satırda fonksiyon yazarken lambda kullanıyoruz.
vectorized = np.vectorize(func)
vectorized(myMat)

array([[25, 64],
       [81, 25],
       [ 0,  0]])

In [11]:
myMat

array([[5, 8],
       [9, 5],
       [0, 0]])

In [7]:
def func(x):  # Normalde fonksiyonu bu şekilde yazıyoruz.
    y=x**2
    return(y)

In [8]:
func(4)

16

In [12]:
m = np.array([[2,4,6,8],[8,10,12,13],[14,16,18,20]])
print(m)
print(f"Minimum değer: {m.min()}")
print(f"Maksimum değer: {m.max()}")
print(f"Ortalama değer: {m.mean()}")
print(f"Toplam değer: {m.sum()}")
print(f"Varyans değeri: {m.var()}")
print(f"Standart Sapma değeri: {m.std()}")

[[ 2  4  6  8]
 [ 8 10 12 13]
 [14 16 18 20]]
Minimum değer: 2
Maksimum değer: 20
Ortalama değer: 10.916666666666666
Toplam değer: 131
Varyans değeri: 28.57638888888889
Standart Sapma değeri: 5.345688813323208


In [13]:
m.reshape(12,1)  # reshape yaparken size'a dikkat. Yukarıdaki 3x4 bu da 12x1. Çarpımları 12 olmalı her durumda

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [ 8],
       [10],
       [12],
       [13],
       [14],
       [16],
       [18],
       [20]])

In [15]:
m.reshape(6,2)

array([[ 2,  4],
       [ 6,  8],
       [ 8, 10],
       [12, 13],
       [14, 16],
       [18, 20]])

In [16]:
# -1 değeri ile yatay düzlemde kolon oluşturur
m.reshape(6,-1)    # -1 yazdığımız yeri size'a uygun olarak kendiliğinden yazıyor. Burada aslında6x2

array([[ 2,  4],
       [ 6,  8],
       [ 8, 10],
       [12, 13],
       [14, 16],
       [18, 20]])

In [18]:
# Tek boyutlu olarak tüm değerin gösterimi
m.reshape(12)

array([ 2,  4,  6,  8,  8, 10, 12, 13, 14, 16, 18, 20])

In [19]:
# Ayrıca flatten yöntemi ile de bu tek boyutlu yapılabilir
m.flatten()

array([ 2,  4,  6,  8,  8, 10, 12, 13, 14, 16, 18, 20])

In [20]:
# Matrisin transpoze edilmesi... T ya da transpose kullanılır. Satırı sütuna çeviriyor, sütunu da satıra.
m.T

array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18],
       [ 8, 13, 20]])

In [21]:
# Bir dizinin transpoze edilerek vektörleştirilmesi. Tek satır tek sütun oldu.
print(np.array([[1,2,3,4,5]]).T)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [22]:
m = np.array([[2,4],[8,10]])
m

array([[ 2,  4],
       [ 8, 10]])

In [23]:
# Determinant hesaplama
np.linalg.det(m)

-11.999999999999995

In [24]:
v1 = np.array([2,4,6])
v2 = np.array([3,5,7])

# dot product hesaplama
np.dot(v1,v2)

# @ işareti ile dot product hesaplama
print(v1 @ v2)

68


In [25]:
# Matrisin tersini bulan fonksiyon.
print(np.linalg.inv(m))

[[-0.83333333  0.33333333]
 [ 0.66666667 -0.16666667]]


In [26]:
np.dot(m,np.linalg.inv(m))    # Bir matrisin kendiyle tersinin çarpımı birim matrisi verir. (eye)

array([[1., 0.],
       [0., 1.]])

In [31]:
x1=np.linspace(0,10, 20, endpoint=False)  # 0-10 arasını 20 sayı ile lineer doldur. 
x1                                       # Endpoint=False....Sondaki değeri dikkate alma.

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [33]:
x1=np.linspace(0,10, 20, endpoint=True)  # Sondaki elemanı dikkate al. 
x1  

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [28]:
np.logspace(2.0, 3.0, num=5)   # Logaritmik olarak doldur. 10 üzeri 2 ile 10 üzeri 3 arasını

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [29]:
x1[0]=100

In [30]:
x1

array([100. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5])

In [34]:
np.delete(x1, 1)   # 1i elemanını sildirebiliriyoruz.

array([ 0.        ,  1.05263158,  1.57894737,  2.10526316,  2.63157895,
        3.15789474,  3.68421053,  4.21052632,  4.73684211,  5.26315789,
        5.78947368,  6.31578947,  6.84210526,  7.36842105,  7.89473684,
        8.42105263,  8.94736842,  9.47368421, 10.        ])

In [35]:
# Matrix oluşturma
myArr = np.array([[17,21,18,11],[43,57,36,231],[911,65,831,117]])
print(myArr)
myArr

[[ 17  21  18  11]
 [ 43  57  36 231]
 [911  65 831 117]]


array([[ 17,  21,  18,  11],
       [ 43,  57,  36, 231],
       [911,  65, 831, 117]])

In [36]:
np.delete(myArr, 1, axis=0)  # axis 0 olrsa tüm satır, 1 olursa tüm sütun. Burada 1. indexteki satırı sildik.

array([[ 17,  21,  18,  11],
       [911,  65, 831, 117]])

In [37]:
np.delete(myArr, 1, axis=1)  #bunu bir değişkene eşitlemezsek değişiklik kalıcı olmaz.

array([[ 17,  18,  11],
       [ 43,  36, 231],
       [911, 831, 117]])